version: "3.8"
services:
  mongo:
    image: mongo:6.0
    container_name: backoffice-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data                             # so mongoimport can see /data/*.csv

  neo4j:
    image: neo4j:5
    container_name: backoffice-neo4j
    ports:
      - "7474:7474"    # HTTP
      - "7687:7687"    # Bolt
    environment:
      NEO4J_AUTH: "neo4j/YourPassword"
    volumes:
      - ./data:/var/lib/neo4j/import             # Neo4j LOAD CSV looks here
