version: '3.8'
services:
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j:5.3
    ports:
      - "7474:7474"    # HTTP UI
      - "7687:7687"    # Bolt
    environment:
      NEO4J_AUTH: "neo4j/YourPassword"

volumes:
  mongo_data:
