
services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data

  neo4j:
    image: neo4j:5
    environment:
      - NEO4J_AUTH=neo4j/secret
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - neo4j_data:/data

  app:
    build: .
    depends_on:
      - mongo
      - neo4j
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000

volumes:
  neo4j_data:
